---
pvjjk_1vos_niinisalo:
  hosts:
    argo.aito.tjas:
      hostname: argo.aito.tjas
    olympus.juva.tjas:
      hostname: olympus.juva.tjas
  vars:
    ansible_python_interpreter: /usr/bin/python3
